config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :offers do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:destroy, :edit, :update]
  get "dashboard", to: "dashboard#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :offer
  belongs_to :user
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  validates :address, :name, :category, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :offers, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?

  after_action :verify_authorized, except: [:index, :dashboard], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

#we might not in need of all these actions, but at least we need the create, as every new booking will be reflected on the offer's show controle

def index
  @bookings = Booking.all
end

def new
  @booking = Booking.new
end

def create
  @booking = Booking.new(booking_params)
  @booking.user = current_user
  @offer = Offer.find(params[:offer_id])
  @booking.offer = @offer
  authorize @booking
  if @booking.save
    redirect_to dashboard_path
  else
    render :new
  end
end

def edit
  @booking = Booking.find(params[:id])
  authorize @booking
end

def update
  @booking = Booking.find(params[:id])
  @booking.update(booking_params)
  authorize @booking
  redirect_to dashboard_path
end

def destroy
  @booking = Booking.find(params[:id])
  @booking.destroy
  authorize @booking
  redirect_to dashboard_path
end

private

def booking_params
  params.require(:booking).permit(:date, :offer_id, :user_id)
end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def dashboard
    @bookings = Booking.where(user_id:"#{current_user.id}")
    @offers = Offer.where(user_id:"#{current_user.id}")
  end

  def destroy
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @offers = policy_scope(Offer)
    if params[:category]
      @offers = Offer.where(category: params[:category])
    elsif params[:query].present?
      sql_query = " \
        offers.name ILIKE :query \
        OR offers.category ILIKE :query \
        OR users.first_name ILIKE :query \
        OR users.last_name ILIKE :query \
        Or offers.address ILIKE :query \
      "
      @offers = Offer.joins(:user).where(sql_query, query: "%#{params[:query]}%")
    else
      @offers = Offer.all
    end
    @markers = @offers.geocoded.map do |offer|
      {
        lat: offer.latitude,
        lng: offer.longitude,
        info_window: render_to_string(partial: "info_window", locals: { offer: offer })
      }
    end
  end

  def new
    @offer = Offer.new
    authorize @offer
  end

  def show
    @offer = Offer.find(params[:id])
    @booking = Booking.new
    authorize @offer
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
    authorize @offer
    if @offer.save
      redirect_to offers_path
    else
      render :new
    end
  end

  def edit
    @offer = Offer.find(params[:id])
    authorize @offer
  end

  def update
    @offer = Offer.find(params[:id])
    @offer.update(offer_params)
    authorize @offer
    redirect_to dashboard_path
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy
    authorize @offer
    redirect_to dashboard_path
  end

  private

  def offer_params
    params.require(:offer).permit(:name, :category, :description, :user_id, :photo, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/dashboard.html.erb
<div class="container col-10">
  <br>
  <h1 class="text-left">My profile</h1>
  <br>
  <div class="row col-3">
    <div class="d-flex">
      <div class="p-1 col-6"><%= cl_image_tag current_user.photo.key, height: 150, width: 150, crop: :fill, radius: :max, background: "#f8edeb" %></div>
      <div class="p-5">
        <h3><%= current_user.first_name %></h3>
        <h3><%= current_user.last_name %></h3>
        <br>
      </div>
    </div>
  </div>
</div>

<div class="container col-10" style="background-color: white;">
  <div class="container col-12">
    <br>
    <h2>My reservations</h2>
    <br>
    <table class="table table-responsive-xl table-hover">
      <thead>
        <tr>
          <th scope="col">Date</th>
          <th scope="col">Session</th>
          <th scope="col">Professor</th>
          <th scope="col">Address</th>
          <th scope="col" style="width: 250px; text-align: center;">Edit</th>
        </tr>
      </thead>
      <tbody>
        <% @bookings.each do |booking| %>
        <tr>
          <th scope="row" style="vertical-align: middle;"><%= booking.date.strftime("%d-%m-%Y")%></th>
          <td style="vertical-align: middle;"><%= booking.offer.name %></td>
          <td style="vertical-align: middle;"><%= booking.offer.user.first_name %></td>
          <td style="vertical-align: middle;"><%= booking.offer.address %></td>
          <td style="display: flex; justify-content: space-evenly;"><%= link_to 'delete', booking_path(booking), method: :delete, data: { confirm: "Are you sure to cancel your reservation?"}, style:'padding-left: 20px; padding-right: 20px', class: "btn btn-secondary"%>
            <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModal" style="padding-left: 20px; padding-right: 20px">update</button>

                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Update your rdv date</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        <%= simple_form_for(booking) do |f| %>
                          <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"} %>
                          <%= f.submit class: "btn btn-primary text-center" %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
          </td>
        </tr>
        <% end  %>
      </tbody>
    </table>
    <br>
    <%= link_to "back", offers_path, class: "btn btn-secondary", style:"font-size: 20px; padding-left: 20px; padding-right: 20px" %>
    <br>
    <br>
  </div>
</div>
<br>
<div class="container col-10" style="background-color: white; margin-bottom: 20px;">
  <div class="container col-12">
    <br>
    <h2>My offers</h2>
    <br>
    <table class="table table-responsive-xl table-hover">
      <thead>
        <tr>
          <th scope="col">Session</th>
          <th scope="col">Description</th>
          <th scope="col">Address</th>
          <th scope="col">Photo</th>
          <th scope="col" style="width: 250px; text-align: center;">Edit</th>
        </tr>
      </thead>
      <tbody>
          <% @offers.each do |offer| %>
          <tr>
            <td style="vertical-align: middle;"><%= offer.name %></td>
            <td style="vertical-align: middle;"><%= offer.description %></td>
            <td style="vertical-align: middle;"><%= offer.address %></td>
            <td style="vertical-align: middle;"><%= offer.photo.filename %></td>
            <td style="display: flex; justify-content: space-evenly;"><%= link_to 'delete', offer_path(offer), method: :delete, data: { confirm: "Are you sure you want to delete this offer?"}, style:'padding-left: 20px; padding-right: 20px', class: "btn btn-secondary"%>
            <%= link_to 'Update', edit_offer_path(offer), style:'padding-left: 20px; padding-right: 20px', class: "btn btn-secondary"%></td>
          </tr>
          <% end  %>
      </tbody>
    </table>
    <br>
    <%= link_to "back", offers_path, class: "btn btn-secondary", style:"font-size: 20px; padding-left: 20px; padding-right: 20px" %>
    <br>
    <br>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RELAXATIONSession</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="wrapper">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/offers/_info_window.html.erb
<div style="background-color: antiquewhite">
  <h2><%= offer.name %></h2>
  <p><%= offer.address %></p>
</div>

app/views/offers/edit.html.erb
<div class="container justify-content-center">
  <br>
  <h1 class="text-center">Edit your offer</h1>
  <div>
    <div class="container col-8">
      <%= simple_form_for @offer do |f| %>
        <%= f.input :category, collection: ["Meditation", "Massage", "Yoga"]%>
        <%= f.input :name, placeholder: 'ex: 5 minutes yoga' %>
        <%= f.input :description %>
        <%= f.input :address %>
        <%= f.input :photo, as: :file, label: "Add an image" %>
        <%= f.submit "Confirm", class: "btn btn-primary" %> <%= link_to "back", dashboard_path, class: "btn btn-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/offers/index.html.erb
<div style="margin-left: 30px">
  <br>
  <h1 class="text-left">Discover our Offers</h1>
</div>
<div class="container col-12">
  <div>
    <div class="row">
    <div class="col-12 col-lg-8" style="display: flex; flex-wrap: wrap; justify-content: center;">
      <% @offers.each do |offer| %>
        <div class="card-offer">
          <div class="card-image">
            <%= cl_image_tag offer.photo.key, height: 150, width: 500, crop: :fill %>
          </div>
          <div class="card-offer-infos">
            <div>
              <h2 style="font-size: 20px;"><%= offer.name %></h2>
              <p style="font-size: 15px;"><%= offer.category %></p>
              <p class="btn btn-light" style="font-size: 12px;"><%= link_to 'Details', offer_path(offer), class:"black_link" %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col-12 col-lg-4">
      <div id="map"
        style="width: 100%; height: 600px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      Hi, there
      </div>
    </div>
    </div>
  </div>
</div>

<div style="display: flex; justify-content: space-between; margin: 15px;">
  <p class="text-left"><%= link_to "back", root_path, class: "btn btn-secondary", style:"font-size: 20px; padding-left: 20px; padding-right: 20px;" %>
</div>

app/views/offers/new.html.erb
<div class="container justify-content-center">
  <br>
  <h1 class="text-center">Your offer</h1>
  <div>
    <div class="container col-8">
      <%= simple_form_for @offer, remote: true do |f| %>
        <%= f.input :category, collection: ["Meditation", "Massage", "Yoga"]%>
        <%= f.input :name, placeholder: 'ex: 5 minutes yoga' %>
        <%= f.input :description %>
        <%= f.input :address, id:"offer_address" %>
        <%= f.input :photo, as: :file, label: "Add an image" %>
        <%= f.submit "Confirm", class: "btn btn-primary" %> <%= link_to "back", offers_path, class: "btn btn-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/offers/show.html.erb
<div class="container-show" style="padding-left: 100px; padding-right: 100px;">
  <br>
  <h1 style="padding-left: 80px;">You will love this selection</h1>
  <br>
  <div class="card-product">
    <div class="card-product-container">
      <div class="card-product-infos" style="font-size: 17px;">
        <h3 class="text-center"> Book your <%= @offer.category %> Session now!</h3>
        <h3 class="text-center", style="margin-top: 10px;"> Discover the "<%= @offer.name %>" created by <%= @offer.user.first_name %></h3>
        <h2 style="font-size: 20px;"> Description: </h2>
        <%= @offer.description %>
        <h2 style="font-size: 20px; margin-top: 10px;"> Address: </h2>
        <%= @offer.address %>
      </div>
      <div style="display: flex; justify-content: center;">
        <br>
        <button type="button" class="btn btn-light" data-toggle="modal" data-target="#exampleModal" style="font-size: 20px;">reserve</button></p>
      </div>
    </div>
    <img class="card-image" style="background-image: url('<%= cl_image_path @offer.photo.key, height: 300, width: 400, crop: :fill %>')" />
  </div>
  <br>
  <div style="display: flex; justify-content: space-between; margin: 15px;">
  <p class="text-left"><%= link_to "back", offers_path, class: "btn btn-secondary", style:"font-size: 20px; padding-left: 20px; padding-right: 20px;" %>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Reserve the selected session</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h4>"<%= @offer.name %>" will cost you <% credit= rand (10) %> <%= credit %> credits, do you confirm your reservation?</h4>
        <%= simple_form_for [@offer, @booking] do |f| %>
        <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <p class="text-center"><%= f.submit class: "btn btn-secondary" %></p>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_url('Bienetre')%>)">
  <div class="container">
    <div>
      <h1>Welcome for a Relaxation Session</h1>
      <p>Relax and discover our selection of meditation, yoga and massage <span style='font-size:20px;'>&#128524;</span></p>
      <br>
      <p class="btn btn-light"><%= link_to "Discover now", offers_path, class:"black_link" %></p>
    </div>
    <div class="container-search">
      <%= form_tag offers_path, class:"d-flex my-4", method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search your session, your activity or your professor"
      %>
      <%= submit_tag "Search", class: "btn btn-secondary px-5" %>
      <% end %>
    </div>
  </div>
</div>

<div class="container" style="margin-top: 20px">
  <div class="justify-content-around">
    <div class="cards">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_url('Meditation')%>)">
     <%= link_to "Meditation", offers_path(category: "Meditation") %>
      </div>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_url('Massage')%>)">
      <%= link_to "Massage", offers_path(category: "Massage") %>
      </div>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_url('Yoga')%>)">
      <%= link_to "Yoga", offers_path(category: "Yoga") %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer col-12">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Just Relax & Take good care <i class="fas fa-heart"></i> of yourself!
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag asset_url('Lotus') %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <h1 id="navbar-title">Relaxation Session</h1>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <div id="nav-email"><%= current_user.email%></div>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link grey_link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Offers", offers_path, class: "nav-link grey_link" %>
          </li>
          <li class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "New Offer", new_offer_path(@user), class: "dropdown-item black_link" %>
              <%= link_to "All Offers", offers_path, class: "dropdown-item black_link" %>
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item black_link" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item black_link" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Discover our offers", offers_path, class: "nav-link black_link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link black_link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>